services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Pepsit36\ApiHelperBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Kernel.php}'

    Pepsit36\ApiHelperBundle\Normalizer\:
            resource: '../../Normalizer'
            tags:
                - { name: exception.normalizer }

    Pepsit36\ApiHelperBundle\EventListener\KernelController\RequestFormHandlerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    pepsit36.apihelper.listener.exception_listener:
        class: Pepsit36\ApiHelperBundle\EventListener\KernelException\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
